---
apiVersion: v1
kind: Service
metadata:
  name: wisp-js
  namespace: umemory
  labels:
    app: wisp-js
spec:
  type: ClusterIP
  selector:
    app: wisp-js
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80
